title: Jeff CLI
email: support@example.com
description: >-
  Jeff is your friendly pal for CLI-based workflows.
baseurl: ""
url: ""
theme: minima
markdown: kramdown
header_pages:
  - downloads.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  sass_dir: assets/css
  style: compressed
exclude:
  - vendor
