title: Jeff CLI
email: support@example.com
description: >-
  Jeff is your friendly pal for CLI-based workflows.
baseurl: "/jeff"
url: "https://micwin.github.io"
theme: minima
markdown: kramdown
header_pages:
  - downloads.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  sass_dir: assets/css
  style: compressed
exclude:
  - .bundle
  - Gemfile
  - Gemfile.lock
  - vendor
  - work
  - dist
  - tmp
  - scripts
  - src
  - tests.d
  - doc
  - README.md
